### PR TITLE
resource group entitlement check fix and detecting changes fix

### PR DESCRIPTION
**Pull request by stikkireddy**
Entitlements for resource groups had typos and logic for detecting changes was not working correctly. This fix resolves those issues.

### CODE REVIEW

**Review by alexott — APPROVED** [review]
lgtm from code perspective, can we add a test to cover that changes?

**Review by nfx — CHANGES_REQUESTED** [review]
Code looks good, but we have to get unit tests to cover these changes.

**Comment by stikkireddy** [comment]
@nfx @alexott sure I can go ahead and add a unit test to cover the update case.

**Comment by nfx** [comment]
hi @stikkireddy, do you have any updates on the test coverage?

**Comment by stikkireddy** [comment]
@nfx i should have some time later today and tomorrow to work on this.

**Comment by stikkireddy** [comment]
@nfx everything should be up to date now with coverage of resource_group

**Review by alexott — APPROVED** [review]

**Review by nfx — APPROVED** [review]

**Pull request merged**
