### PR TITLE
bug fix - use ARM_SUBSCRIPTION_ID env var for azure_auth if exists

### PR DESCRIPTION
**Pull request by masoncusack**
Found a bug described in https://github.com/databrickslabs/terraform-provider-databricks/issues/164

The wrong (empty) environment variable is retrieved if a user uses ARM_SUBSCRIPTION_ID for azure_auth. `provider.go` has been update to correctly retrieve ARM_SUBSCRIPTION_ID.

This resulted in 404 errors for workspace resources because our subscription ID was not being added to GET request URLs.

### CODE REVIEW

**Comment by jjcollinge** [comment]
@masoncusack not sure why my commit is in this PR?

**Comment by nfx** [comment]
@masoncusack this will be fixed more holistically in #158

**Comment by masoncusack** [comment]
> Can you remove changes for resource_databricks_job.go for this PR please. That should be tested and resolved in another PR.

Done :) Is this going to be used anymore though? Given:

> @masoncusack this will be fixed more holistically in #158

**Comment by nfx** [comment]
@masoncusack this PR is no longer needed. closing this one.

**Pull request closed without merging**
