### PR TITLE
Add AKV backend for databricks_secret_scope

### PR DESCRIPTION
**Pull request by nfx**
Implements issue #369

On Azure it's possible to create manage secrets in Azure Key Vault and have use Azure Databricks secret redaction & access control functionality for reading them. There has to be a single Key Vault per single secret scope.

-> **Note** Currently, it's only possible to create Azure Key Vault scopes with Azure CLI authentication and not with Service Principal. That means, `az login --service-principal --username $ARM_CLIENT_ID --password $ARM_CLIENT_SECRET --tenant $ARM_TENANT_ID` won't work as well. This is the limitation from underlying cloud resources.

```hcl
data "azurerm_client_config" "current" {
}

resource "azurerm_key_vault" "this" {
  name                     = "${var.prefix}-kv"
  location                 = azurerm_resource_group.example.location
  resource_group_name      = azurerm_resource_group.example.name
  tenant_id                = data.azurerm_client_config.current.tenant_id
  soft_delete_enabled      = false
  purge_protection_enabled = false
  sku_name                 = "standard"
  tags                     = var.tags

  access_policy {
    tenant_id = data.azurerm_client_config.current.tenant_id
    object_id = data.azurerm_client_config.current.object_id
    secret_permissions = [
      "delete", "get", "list", "set"
    ]
  }
}

resource "databricks_secret_scope" "kv" {
  name = "keyvault-managed"

  keyvault_metadata {
    resource_id = azurerm_key_vault.this.id
    dns_name = azurerm_key_vault.this.vault_uri
  }
}
```

### CODE REVIEW

**Comment by nfx** [comment]
@favoretti ^^

**Comment by nfx** [comment]
@favoretti, @markhoiland, @alaczynski, @sabino, @allaC, @evaimitico, @lukerosser, @gerryhernandez, @fedragon, @lachie-white , @jordanjennings , @sdebruyn, ^^

**Comment by sdebruyn** [comment]
This is awesome. Thank you @nfx! I'll make some time to test it this week

**Comment by fedragon** [comment]
Awesome @nfx!

**Comment by jordanjennings** [comment]
@nfx Is there any additional documentation you can point to about the service principal limitation? We run terraform via CI/CD and use a service principal for it, which means this feature will not work for us, correct? Is there any known workaround?

**Comment by nfx** [comment]
@jordanjennings workarounds are same as before - use Databricks-backed scopes or copy secrets through data sources. Keep raising creation of AKV-backed scopes by Service Principals through API to your Databricks representatives :)

**Comment by nfx** [comment]
PASS access/acceptance.TestAccSecretScopeResource (14.32s)

**Pull request merged**
